### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by gabrielprioli**
- Duplicated "http"
- Include a reference to the version in the gzipped release archive
- Adjust markdown

### CODE REVIEW

**Comment by johannes-b** [comment]
@gabrielprioli the changes look good to me! Many thanks. 

Can you please sign your commit, as explained here: https://github.com/keptn-contrib/dynatrace-service/pull/326/checks?check_run_id=2587878208

Then we are ready to merge it.

**Review by johannes-b — APPROVED** [review]

**Comment by gabrielprioli** [comment]
@johannes-b I think I did the right thing, please take a look again?

**Comment by johannes-b** [comment]
@gabrielprioli you signed the commit correctly, but can you please resolve the conflict in the Readme.md.

**Comment by gabrielprioli** [comment]
@johannes-b conflicts resolved, but I don't know if the merge commit should also be signed?

**Review by johannes-b — APPROVED** [review]
lgtm

**Comment by johannes-b** [comment]
@arthurpitman I will let you know that this change looks good, but I leave it up to you to merge it. :)

**Pull request merged**
